[chore]: In Chinese language, the top navigation bar button needs to …
apache/apisix-website pull request #1024
Opened 2022-04-13 06:45 UTC by juxianzheng

…be translated into Chinese

Fixes: #[Add issue number here]

Changes:

Screenshots of the change:

2022-04-13 13:42 UTC, yzeng25 commented
LGTM except couple some neats.

1. Changes in `yarn.lock` files should not be included. This file should remain the same. Please fix it.
2. Please modify your **pull request title** and **description** to something shorter in length. 

- Something like `chore: add translation for "Resource" button` for the pull request title; 
- Something like `Changes: In Chinese language, the "Resource" button in  navigation bar needs to be translated into - -Chinese` for description would be way better. 
- Delete the `Fixes: #[Add issue number here]` part,  since there is not an issue for it (You can definitely create an issue as well but it is up to you). 
- A couple of screenshots to show the before/after could help as well.

cc @Baoyuantop @guoqqqi @bzp2010 @juzhiyuan @SkyeYoung

2022-04-14 03:39 UTC, juzhiyuan commented on website/i18n/zh/docusaurus-theme-classic/navbar.json
> +    "message": "活动介绍",
```suggestion
    "message": "社区活动",
```

2022-04-14 03:39 UTC, juzhiyuan commented on website/i18n/zh/docusaurus-theme-classic/navbar.json
> +    "message": "社区活动",
![image](https://user-images.githubusercontent.com/2106987/163309049-7882defe-1c50-40ea-ba62-6dcfd2c61a61.png)

```suggestion
    "message": "加入社区",
```

2022-04-14 03:39 UTC, juzhiyuan commented on website/i18n/zh/docusaurus-theme-classic/navbar.json
> +  "item.label.Plugin Hub": {
```suggestion
  "item.label.PluginHub": {
```

2022-04-14 03:39 UTC, juzhiyuan commented on website/i18n/zh/docusaurus-theme-classic/navbar.json
> +    "message": "资源",
```suggestion
    "message": "相关资源",
```

2022-04-15 01:29 UTC, guoqqqi commented
@juxianzheng 
You can see a preview of the changes in this section of the PR, please check it yourself after the changes are made
![image](https://user-images.githubusercontent.com/72343596/163503420-7a422f58-c212-4d86-844a-03d6ee79b150.png)

2022-04-15 01:32 UTC, guoqqqi commented
Here are some other questions
![image](https://user-images.githubusercontent.com/72343596/163503662-c971e3c5-bcec-4105-b5b0-3467eb0e5576.png)

2022-04-15 02:00 UTC, SkyeYoung commented
> Here are some other questions ![image](https://user-images.githubusercontent.com/72343596/163503662-c971e3c5-bcec-4105-b5b0-3467eb0e5576.png)

@guoqqqi  `undefined` has been fixed in #1029.
@juxianzheng pls merge current master into the PR branch. If you encounter some problems, please feel free to ping me :D

2022-04-15 03:42 UTC, juzhiyuan commented
> ### ✅ Deploy Preview for _apache-apisix_ ready!
> Name	Link
> 🔨 Latest commit	[882df08](https://github.com/apache/apisix-website/commit/882df08fa3276563f0ba293d268aeaaf754a60b1)
> 🔍 Latest deploy log	https://app.netlify.com/sites/apache-apisix/deploys/6257d6363f3bb00009631752
> 😎 Deploy Preview	https://deploy-preview-1024--apache-apisix.netlify.app
> 📱 Preview on mobile	
> Toggle QR Code...
> _To edit notification comments on pull requests, go to your [Netlify site settings](https://app.netlify.com/sites/apache-apisix/settings/deploys#deploy-notifications)._

Please note: each PR has its Preview Link, you could see what has been changed.

![image](https://user-images.githubusercontent.com/2106987/163514585-2467ceee-a286-44a0-a671-4bdc2c1d6909.png)

Plugin Hub needs to be updated with "插件市场"

2022-04-19 03:22 UTC, juzhiyuan submitted a review, later dismissed

2022-04-19 03:55 UTC, Baoyuantop commented
> > ### ✅ Deploy Preview for _apache-apisix_ ready!
> > Name	Link
> > 🔨 Latest commit	[882df08](https://github.com/apache/apisix-website/commit/882df08fa3276563f0ba293d268aeaaf754a60b1)
> > 🔍 Latest deploy log	https://app.netlify.com/sites/apache-apisix/deploys/6257d6363f3bb00009631752
> > 😎 Deploy Preview	https://deploy-preview-1024--apache-apisix.netlify.app
> > 📱 Preview on mobile
> > Toggle QR Code...
> > _To edit notification comments on pull requests, go to your [Netlify site settings](https://app.netlify.com/sites/apache-apisix/settings/deploys#deploy-notifications)._
> 
> Please note: each PR has its Preview Link. So you could see what has been changed.
> 
> ![image](https://user-images.githubusercontent.com/2106987/163514585-2467ceee-a286-44a0-a671-4bdc2c1d6909.png)
> 
> Plugin Hub needs to be updated with "插件市场"

I noticed that this issue was not addressed🤔

2022-04-19 09:56 UTC, yzeng25 commented on website/i18n/zh/docusaurus-theme-classic/navbar.json
> +    "description": "Navbar item with label Plugin Hub"
I noticed @juxianzheng has translated it to Chinese, just like other lines. But as @Baoyuantop saw in preview, this part of change does not show up. Need to take a closer look @juzhiyuan @SkyeYoung .

2022-04-19 14:38 UTC, SkyeYoung commented on website/i18n/zh/docusaurus-theme-classic/navbar.json
> +    "description": "Navbar item with label Plugin Hub"
🤔 I'll have a look tomorrow.

2022-04-20 01:22 UTC, Baoyuantop commented on website/i18n/zh/docusaurus-theme-classic/navbar.json
> +    "description": "Navbar item with label Plugin Hub"
And it should be "插件市场"

2022-04-20 01:39 UTC, yzeng25 commented on website/i18n/zh/docusaurus-theme-classic/navbar.json
> +    "description": "Navbar item with label Plugin Hub"
> And it should be "插件市场"

Yeah but you need to figure out getting this part `"message": "插件中心",` to work first. The rest of it is just changing `"插件中心"` to `"插件市场"`.

2022-04-20 02:18 UTC, SkyeYoung commented on website/i18n/zh/docusaurus-theme-classic/navbar.json
> +    "description": "Navbar item with label Plugin Hub"
Here's a space. Emmm, I will change this label to "PluginHub". Wait a moment, I will create a new PR.

2022-04-20 02:29 UTC, SkyeYoung commented on website/i18n/zh/docusaurus-theme-classic/navbar.json
> +    "description": "Navbar item with label Plugin Hub"
It should be fixed in #1043

2022-04-20 03:26 UTC, yzeng25 commented on website/i18n/zh/docusaurus-theme-classic/navbar.json
> +    "description": "Navbar item with label Plugin Hub"
> It should be fixed in #1043

Great :)

2022-04-20 03:35 UTC, SkyeYoung commented
@juzhiyuan we need rerun the preview task to determine if the Plugin Hub's label problem has been fixed.

2022-04-20 05:37 UTC, SkyeYoung commented
@Baoyuantop "插件市场" has been fixed.

2022-04-20 05:38 UTC, guoqqqi approved these changes, later dismissed
LGTM

2022-04-20 05:45 UTC, SkyeYoung requested changes

2022-04-20 05:45 UTC, SkyeYoung commented on website/config/navbar.js
> +        label: 'PluginHub',
Why you modified this file but not merge master into this branch?

2022-04-20 07:20 UTC, guoqqqi requested changes

2022-04-20 07:20 UTC, guoqqqi commented on .github/ISSUE_TEMPLATE/feature_request.md
> +A clear and concise description of any alternative solutions or features you've considered.
Please check the files you have changed before submitting, Don't submit unrelated changes

2022-04-21 06:34 UTC, guoqqqi approved these changes

2022-04-21 06:35 UTC, SkyeYoung approved these changes

2022-04-22 01:56 UTC, Baoyuantop approved these changes

2022-04-22 13:50 UTC, yzeng25 approved these changes
LGTM. I fixed the pull request description as well. Please try to fix them next time :)

Thanks @juxianzheng for your contribution, really appreciate it!

2022-04-24 08:19 UTC, merged