fix: broken responsive behavior on mobile devices
apache/apisix-website pull request #1128
Opened 2022-06-01 16:44 UTC by 1502shivam-singh

Fixes: broken responsive behavior on mobile devices, screenshots below

![image](https://user-images.githubusercontent.com/57267960/171456447-c0b2dad9-b546-4033-b80e-007209cc0b4c.png)
--------------------------------------------------------
![image](https://user-images.githubusercontent.com/57267960/171456635-0686baf7-fb2f-460b-8c64-b1465aa049a7.png)

Changes:

Fixed overflowing content, sizes and visual issues

2022-06-01 22:16 UTC, juzhiyuan commented
cc @SkyeYoung to have a review~

2022-06-02 01:00 UTC, SkyeYoung requested changes

2022-06-02 01:00 UTC, SkyeYoung commented on website/src/css/customTheme.css
> +    font-size: 1.70rem;
```suggestion
    font-size: 1.7rem;
```

2022-06-02 11:46 UTC, SkyeYoung approved these changes

2022-06-03 00:39 UTC, juzhiyuan approved these changes

2022-06-03 03:27 UTC, guoqqqi approved these changes

2022-06-03 11:11 UTC, merged