fix: translated some words and added link style
apache/apisix-website pull request #1418
Opened 2022-11-21 14:19 UTC by uniqie

Fixes: #1400 

Changes:

1. I have rebuilded code.json and translated part of words in it.
2. I have added a little style to 'view all tags'.

Screenshots of the change:

<img width="1317" alt="image" src="https://user-images.githubusercontent.com/48682080/203076429-7b5aea09-1c70-4e9e-967a-bfda49d0a569.png">

2022-11-22 01:26 UTC, SkyeYoung requested changes
Pls translate like a native speaker

2022-11-22 01:26 UTC, SkyeYoung commented on blog/i18n/zh/code.json
> +    "message": "{count}个贴子",
```suggestion
    "message": "{count}篇",
```

2022-11-22 01:26 UTC, SkyeYoung commented on blog/i18n/zh/code.json
> +    "message": "{nPosts}标记为\"{tagName}\"",
```suggestion
    "message": "{nPosts} 被标记为 “{tagName}”",
```

2022-11-22 01:34 UTC, SkyeYoung commented
Also pls add a hover (and visited) style to the link

2022-11-24 01:50 UTC, SkyeYoung commented
> Also pls add a hover (and visited) style to the link

@uniqie pls fix this

2022-11-24 03:02 UTC, uniqie commented
> 
fine🙈

2022-11-24 08:46 UTC, SkyeYoung approved these changes

2022-11-25 01:23 UTC, SylviaBABY approved these changes

2022-11-25 01:27 UTC, merged