docs: add zhengcaiyun-uses-apisix.md
apache/apisix-website pull request #1749
Opened 2023-12-26 07:47 UTC by JYan00

2023-12-28 01:41 UTC, Yilialinn approved these changes

2023-12-28 02:21 UTC, EmilyKeer commented on blog/en/blog/2023/12/26/zhengcaiyun-uses-apisix.md
> +![Optimization_solutions](https://static.apiseven.com/uploads/2023/12/26/Bs0op31X_3.jpg)
"barrel model" in the chart seems to be an incorrect phase; please fix it

2023-12-28 02:24 UTC, EmilyKeer commented on blog/en/blog/2023/12/26/zhengcaiyun-uses-apisix.md
> +![Highway_future](https://static.apiseven.com/uploads/2023/12/26/r0AMeygL_9.jpg)
The shown text should be APISIX, instead of Apisix

2023-12-28 02:34 UTC, EmilyKeer requested changes
A thorough check for terminologies is needed

2024-01-22 01:58 UTC, yzeng25 commented
@JYan00 any update?

2024-01-30 03:31 UTC, yzeng25 approved these changes

2024-02-18 07:05 UTC, guoqqqi approved these changes

2024-02-18 07:05 UTC, merged