docs: add csrf blog
apache/apisix-website pull request #900
Opened 2022-02-23 09:00 UTC by yzeng25

Fixes: #[Add issue number here]

Changes:

Add the blog for CSRF plugin.

2022-02-23 09:36 UTC, hf400159 requested changes

2022-02-23 09:36 UTC, hf400159 commented on website/i18n/zh/docusaurus-plugin-content-blog/2022/02/23/csrf.md
> +Set-Cookie: apisix-csrf-token=eyJyYW5kb20iOjAuNjg4OTcyMzA4ODM1NDMsImV4cGlyZXMiOjcyMDAsInNpZ24iOiJcL09uZEF4WUZDZGYwSnBiNDlKREtnbzVoYkJjbzhkS0JRZXVDQm44MG9ldz0ifQ==;path=/;Expires=Mon, 13-Dec-21 09:33:
The token in the code is too long, it is suggested that the code formatting, or use other words to indicate what this code means.

2022-02-23 09:36 UTC, guitu168 commented on website/i18n/zh/docusaurus-plugin-content-blog/2022/02/23/csrf.md
> +用户需要在对该路由的不安全请求中携带这一 Cookie，并在请求头添加额外的字段携带 Cookie 的内容。字段为插件配置中的 `name` 值，这样的请求才能通过 CSRF 插件的校验。
```suggestion
用户需要在对该路由的不安全请求中携带这一 Cookie，并在请求头添加额外的字段用来携带 Cookie 的内容。字段为插件配置中的 `name` 值，这样的请求才能通过 CSRF 插件的校验。
```

2022-02-23 09:36 UTC, hf400159 commented on website/i18n/zh/docusaurus-plugin-content-blog/2022/02/23/csrf.md
> +curl -i http://127.0.0.1:9080/hello -X POST -H 'apisix-csrf-token: differenteyJyYW5kb20iOjAuNjg4OTcyMzA4ODM1NDMsImV4cGlyZXMiOjcyMDAsInNpZ24iOiJcL09uZEF4WUZDZGYwSnBiNDlKREtnbzVoYkJjbzhkS0JRZXVDQm44MG9
```suggestion
curl -i http://127.0.0.1:9080/hello -X POST -H 'apisix-csrf-token: ${apisix-csrf-token}' -b 'apisix-csrf-token= ${apisix-csrf-token}'
```

2022-02-23 09:36 UTC, hf400159 commented on website/i18n/zh/docusaurus-plugin-content-blog/2022/02/23/csrf.md
> +Set-Cookie: apisix-csrf-token=eyJyYW5kb20iOjAuNjg4OTcyMzA4ODM1NDMsImV4cGlyZXMiOjcyMDAsInNpZ24iOiJcL09uZEF4WUZDZGYwSnBiNDlKREtnbzVoYkJjbzhkS0JRZXVDQm44MG9ldz0ifQ==;path=/;Expires=Mon, 13-Dec-21 09:33:
```suggestion
Set-Cookie: apisix-csrf-token= ${apisix-csrf-token};path=/;Expires=Mon, 13-Dec-21 09:33:55 GMT
```

2022-02-23 09:36 UTC, hf400159 commented on website/i18n/zh/docusaurus-plugin-content-blog/2022/02/23/csrf.md
> +curl -i http://127.0.0.1:9080/hello -X POST -H 'apisix-csrf-token: eyJyYW5kb20iOjAuNjg4OTcyMzA4ODM1NDMsImV4cGlyZXMiOjcyMDAsInNpZ24iOiJcL09uZEF4WUZDZGYwSnBiNDlKREtnbzVoYkJjbzhkS0JRZXVDQm44MG9ldz0ifQ==
ditto

2022-02-23 09:36 UTC, hf400159 commented on website/blog/2022/02/23/csrf.md
> +Set-Cookie: apisix-csrf-token=eyJyYW5kb20iOjAuNjg4OTcyMzA4ODM1NDMsImV4cGlyZXMiOjcyMDAsInNpZ24iOiJcL09uZEF4WUZDZGYwSnBiNDlKREtnbzVoYkJjbzhkS0JRZXVDQm44MG9ldz0ifQ==;path=/;Expires=Mon, 13-Dec-21 09:33:
Please refer to Chinese for modification.

2022-02-24 02:56 UTC, bzp2010 approved these changes

2022-02-24 03:16 UTC, juzhiyuan approved these changes

2022-02-24 03:16 UTC, merged